# Generated by Django 4.2.29 on 2026-04-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('holo_rare', 'Holo Rare'), ('reverse_holo', 'Reverse Holo'), ('double_rare', 'Double Rare'), ('ultra_rare', 'Ultra Rare'), ('illustration_rare', 'Illustration Rare'), ('special_illustration_rare', 'Special Illustration Rare'), ('hyper_rare', 'Hyper Rare'), ('secret_rare', 'Secret Rare'), ('ace_spec', 'ACE SPEC'), ('promo', 'Promo')], max_length=25)),
                ('region', models.CharField(choices=[('en', 'English'), ('jp', 'Japanese'), ('cn', 'Chinese'), ('kr', 'Korean'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese'), ('es', 'Spanish')], default='en', max_length=5)),
                ('card_number', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, upload_to='card_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.set')),
            ],
        ),
    ]
