# Generated by Django 4.2.29 on 2026-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
