# Generated by Django 4.2.29 on 2026-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
