# Generated by Django 4.2.29 on 2026-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_card_name_alter_card_price_alter_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
