# Generated by Django 4.2.29 on 2026-04-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='header_color',
            field=models.CharField(choices=[('#344657', 'Forest'), ('#79ae6f', 'Sage'), ('#4a6fa5', 'Ocean'), ('#7b4f8e', 'Dusk'), ('#8b5e3c', 'Chestnut'), ('#c0545a', 'Berry')], default='#344657', max_length=7),
        ),
    ]
